name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
template: |
  # What's Changed
  $CHANGES
categories:
  - title: '🚀 New features'
    label: 'major'
  - title: '🔧 Changes'
    label: 'minor'
  - title: '🐞 Bug Fixes'
    label: 'patch'

version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'minor'
  patch:
    labels:
      - 'patch'

exclude-labels:
  - 'skip-changelog'

commitish: 'build-webgl'
