name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
template: |
  # What's Changed
  $CHANGES
  ## QA Testing
  * WebGL build can be played [here](https://shirokatake.github.io/apawllo-remake/).
  * Windows build can be downloaded below.

categories:
  - title: '⚡ Breaking'
    label: 'major'
  - title: '🚀 New Features'
    label: 'feature'
  - title: '🐞 Bug Fixes'
    label: 'patch'
  - title: '✨ Workflow Updates'
    label: 'workflow'

version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'feature'
  patch:
    labels:
      - 'patch'

exclude-labels:
  - 'skip-changelog'
