name-template: 'v$RESOLVED_VERSION'
tag-template: 'v$RESOLVED_VERSION'
template: |
  # What's Changed
  $CHANGES
categories:
  - title: '🚀 Breaking'
    label: 'major'
  - title: '✨ New'
    label: 'feature'
  - title: '🐞 Bug Fixes'
    label: 'patch'
  - title: '🔄 Workflow Updates'
    label: 'workflow'

version-resolver:
  major:
    labels:
      - 'major'
  minor:
    labels:
      - 'feature'
  patch:
    labels:
      - 'patch'

exclude-labels:
  - 'skip-changelog'

commitish: 'build-webgl'
